services:
  go-api:
    build:
      context: ./app
    ports:
      - "8080:8080"
    depends_on:
      - pgdb

  pgdb:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
