services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '55432:5432'
    restart: on-failure

  # dbmate:
  #   image: ghcr.io/amacneil/dbmate
  #   environment:
  #     DB_URL: ${DB_URL}
  #   volumes:
  #     - ./app/database:/db
  #   command: ["migrate", "-u", "${DB_URL}", "-no-dump-schema"]
  #   network_mode: host
  #   restart: "no"
  #   depends_on:
  #     - postgres

  go-api:
    image: golang:1.22
    working_dir: /app
    volumes:
    - ./app:/app
    ports:
      - "8080:8080"
    command: ["go", "run", "."]
    depends_on:
      - postgres
      # - dbmate
    restart: on-failure

  # curl-tests:
  #   build:
  #     context: curl-tests
  #     dockerfile: Dockerfile
  #   working_dir: /usr/app/curl-tests
  #   volumes:
  #     - ./curl-tests:/usr/app/curl-tests
  #   depends_on:
  #     - go-api
  #   restart: on-failure

networks:
  default:
    name: goyave-backend
    external: true