services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '55432:5432'
    restart: on-failure

  # go-api:
  #   image: golang:1.22
  #   # working_dir: /app
  #   volumes:
  #   - ./app:/app
  #   ports:
  #     - "8080:8080"
  #   build: .
  #   # command: ["go", "run", "."]
  #   depends_on:
  #     - postgres
  #   restart: on-failure
networks:
  default:
    name: goyave-backend
    external: true