
services:

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3f4f2770c42a8efddc80e61da8d7c9f71cfe2eb03ff6040542ad24a42192731f4af7e875ca5fc8736240
    ports:
      - '55432:5432'
    restart: on-failure

  # go-api:
  #   build:
  #     context: ./app
  #   env_file:
  #     - .env
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres
  #   restart: on-failure

networks:
  default:
    name: goyave-backend
    external: true