
services:

  postgres:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '55432:5432'
    restart: on-failure

  # go-api:
  #   build:
  #     context: ./app
  #   env_file:
  #     - .env
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres
  #   restart: on-failure

networks:
  default:
    name: goyave-backend
    external: true