services:

  # pgdb:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: postgres
  #   ports:
  #     - "55432:5432"

  go-api:
    build:
      context: ./app
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - tranched
    # depends_on:
    #   - pgdb

networks:
  tranched:
    external: true